"use client";
import { useMemo } from "react";
import type { StarWithPosition } from "@/types";

const MILLION = 1_000_000;

const REAL_GALAXIES: Array<
  Pick<
    StarWithPosition,
    | "catalog_id"
    | "common_name"
    | "scientific_name"
    | "ra"
    | "dec"
    | "magnitude"
    | "constellation"
    | "star_type"
    | "distance_light_years"
    | "thumbnail_url"
  >
> = [
  {
    catalog_id: "M31",
    common_name: "Andromeda Galaxy",
    scientific_name: "NGC 224",
    ra: 10.684708,
    dec: 41.26875,
    magnitude: 3.44,
    constellation: "Andromeda",
    star_type: "Spiral Galaxy",
    distance_light_years: 2.54 * MILLION,
    thumbnail_url: "https://science.nasa.gov/wp-content/uploads/2023/04/m31-jpg.webp",
  },
  {
    catalog_id: "M33",
    common_name: "Triangulum Galaxy",
    scientific_name: "NGC 598",
    ra: 23.4621,
    dec: 30.6599,
    magnitude: 5.72,
    constellation: "Triangulum",
    star_type: "Spiral Galaxy",
    distance_light_years: 2.73 * MILLION,
    thumbnail_url: "https://science.nasa.gov/wp-content/uploads/2023/04/m33-jpg.webp",
  },
  {
    catalog_id: "M81",
    common_name: "Bode's Galaxy",
    scientific_name: "NGC 3031",
    ra: 148.8882,
    dec: 69.0653,
    magnitude: 6.94,
    constellation: "Ursa Major",
    star_type: "Spiral Galaxy",
    distance_light_years: 11.8 * MILLION,
  },
  {
    catalog_id: "M82",
    common_name: "Cigar Galaxy",
    scientific_name: "NGC 3034",
    ra: 148.9697,
    dec: 69.6797,
    magnitude: 8.41,
    constellation: "Ursa Major",
    star_type: "Irregular Galaxy",
    distance_light_years: 12 * MILLION,
  },
  {
    catalog_id: "M51",
    common_name: "Whirlpool Galaxy",
    scientific_name: "NGC 5194",
    ra: 202.4842,
    dec: 47.2306,
    magnitude: 8.36,
    constellation: "Canes Venatici",
    star_type: "Spiral Galaxy",
    distance_light_years: 31 * MILLION,
    thumbnail_url: "https://science.nasa.gov/wp-content/uploads/2023/04/m51-jpg.webp",
  },
  {
    catalog_id: "M101",
    common_name: "Pinwheel Galaxy",
    scientific_name: "NGC 5457",
    ra: 210.8023,
    dec: 54.3489,
    magnitude: 7.86,
    constellation: "Ursa Major",
    star_type: "Spiral Galaxy",
    distance_light_years: 21 * MILLION,
  },
  {
    catalog_id: "M104",
    common_name: "Sombrero Galaxy",
    scientific_name: "NGC 4594",
    ra: 189.9976,
    dec: -11.6231,
    magnitude: 8,
    constellation: "Virgo",
    star_type: "Lenticular Galaxy",
    distance_light_years: 29.3 * MILLION,
    thumbnail_url: "https://science.nasa.gov/wp-content/uploads/2023/04/m104-jpg.webp",
  },
  {
    catalog_id: "M87",
    common_name: "Virgo A",
    scientific_name: "NGC 4486",
    ra: 187.7059,
    dec: 12.3911,
    magnitude: 8.63,
    constellation: "Virgo",
    star_type: "Elliptical Galaxy",
    distance_light_years: 53.5 * MILLION,
  },
  {
    catalog_id: "M64",
    common_name: "Black Eye Galaxy",
    scientific_name: "NGC 4826",
    ra: 194.1821,
    dec: 21.6827,
    magnitude: 8.52,
    constellation: "Coma Berenices",
    star_type: "Spiral Galaxy",
    distance_light_years: 17 * MILLION,
  },
  {
    catalog_id: "M65",
    common_name: "Leo Triplet Galaxy",
    scientific_name: "NGC 3623",
    ra: 169.7332,
    dec: 13.0922,
    magnitude: 9.3,
    constellation: "Leo",
    star_type: "Barred Spiral Galaxy",
    distance_light_years: 35 * MILLION,
  },
  {
    catalog_id: "M66",
    common_name: "Leo Triplet Galaxy",
    scientific_name: "NGC 3627",
    ra: 170.0624,
    dec: 12.9915,
    magnitude: 8.92,
    constellation: "Leo",
    star_type: "Barred Spiral Galaxy",
    distance_light_years: 36 * MILLION,
  },
  {
    catalog_id: "NGC 3628",
    common_name: "Hamburger Galaxy",
    scientific_name: "NGC 3628",
    ra: 170.0708,
    dec: 13.5894,
    magnitude: 9.5,
    constellation: "Leo",
    star_type: "Spiral Galaxy",
    distance_light_years: 35 * MILLION,
  },
  {
    catalog_id: "M94",
    common_name: "Croc's Eye Galaxy",
    scientific_name: "NGC 4736",
    ra: 192.7211,
    dec: 41.1202,
    magnitude: 8.24,
    constellation: "Canes Venatici",
    star_type: "Spiral Galaxy",
    distance_light_years: 16 * MILLION,
  },
  {
    catalog_id: "M63",
    common_name: "Sunflower Galaxy",
    scientific_name: "NGC 5055",
    ra: 198.9555,
    dec: 42.0293,
    magnitude: 8.59,
    constellation: "Canes Venatici",
    star_type: "Spiral Galaxy",
    distance_light_years: 29 * MILLION,
  },
  {
    catalog_id: "M83",
    common_name: "Southern Pinwheel Galaxy",
    scientific_name: "NGC 5236",
    ra: 204.2538,
    dec: -29.8658,
    magnitude: 7.54,
    constellation: "Hydra",
    star_type: "Barred Spiral Galaxy",
    distance_light_years: 15 * MILLION,
  },
  {
    catalog_id: "M49",
    common_name: "Virgo Cluster Galaxy",
    scientific_name: "NGC 4472",
    ra: 187.4449,
    dec: 8.0004,
    magnitude: 8.39,
    constellation: "Virgo",
    star_type: "Elliptical Galaxy",
    distance_light_years: 56 * MILLION,
  },
  {
    catalog_id: "M60",
    common_name: "Virgo Cluster Galaxy",
    scientific_name: "NGC 4649",
    ra: 190.9167,
    dec: 11.5527,
    magnitude: 8.79,
    constellation: "Virgo",
    star_type: "Elliptical Galaxy",
    distance_light_years: 57 * MILLION,
  },
  {
    catalog_id: "M95",
    common_name: "Leo I Group Galaxy",
    scientific_name: "NGC 3351",
    ra: 160.9904,
    dec: 11.7038,
    magnitude: 9.7,
    constellation: "Leo",
    star_type: "Barred Spiral Galaxy",
    distance_light_years: 33 * MILLION,
  },
  {
    catalog_id: "M96",
    common_name: "Leo I Group Galaxy",
    scientific_name: "NGC 3368",
    ra: 161.6906,
    dec: 11.8199,
    magnitude: 9.2,
    constellation: "Leo",
    star_type: "Spiral Galaxy",
    distance_light_years: 31 * MILLION,
  },
  {
    catalog_id: "M105",
    common_name: "Leo I Group Galaxy",
    scientific_name: "NGC 3379",
    ra: 161.9567,
    dec: 12.5816,
    magnitude: 9.3,
    constellation: "Leo",
    star_type: "Elliptical Galaxy",
    distance_light_years: 36.6 * MILLION,
  },
  {
    catalog_id: "NGC 253",
    common_name: "Sculptor Galaxy",
    scientific_name: "NGC 253",
    ra: 11.888,
    dec: -25.2882,
    magnitude: 7.1,
    constellation: "Sculptor",
    star_type: "Spiral Galaxy",
    distance_light_years: 11.4 * MILLION,
  },
  {
    catalog_id: "NGC 5128",
    common_name: "Centaurus A",
    scientific_name: "NGC 5128",
    ra: 201.3651,
    dec: -43.0191,
    magnitude: 6.84,
    constellation: "Centaurus",
    star_type: "Elliptical Galaxy",
    distance_light_years: 12 * MILLION,
  },
  {
    catalog_id: "NGC 4945",
    common_name: "Caldwell 83",
    scientific_name: "NGC 4945",
    ra: 196.3587,
    dec: -49.4682,
    magnitude: 9.3,
    constellation: "Centaurus",
    star_type: "Barred Spiral Galaxy",
    distance_light_years: 12 * MILLION,
  },
  {
    catalog_id: "LMC",
    common_name: "Large Magellanic Cloud",
    scientific_name: "ESO 56-115",
    ra: 80.8942,
    dec: -69.7561,
    magnitude: 0.9,
    constellation: "Dorado/Mensa",
    star_type: "Irregular Galaxy",
    distance_light_years: 163_000,
  },
  {
    catalog_id: "SMC",
    common_name: "Small Magellanic Cloud",
    scientific_name: "NGC 292",
    ra: 13.1867,
    dec: -72.8286,
    magnitude: 2.7,
    constellation: "Tucana",
    star_type: "Irregular Galaxy",
    distance_light_years: 200_000,
  },
];

export function useCatalogGalaxies(): StarWithPosition[] {
  return useMemo(
    () =>
      REAL_GALAXIES.map((galaxy, index) => ({
        id: -500_000 - index,
        ...galaxy,
        galaxy_name: galaxy.common_name || galaxy.catalog_id,
        object_kind: "galaxy",
        ra_unit: "degrees",
        color_index_bv: 0.72,
        is_visible_naked_eye: (galaxy.magnitude ?? 99) <= 6.5,
        is_named: false,
        is_available_for_naming: false,
        registry_status: "Available",
        is_visible: false,
      })),
    []
  );
}
